name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn lint
      - run: yarn test
      - run: yarn ts
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn workspace e2e playwright install-deps
      - run: yarn workspace e2e playwright install chromium
      - run: yarn workspace e2e test
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-results
          path: e2e/test-results
