name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn lint
      - run: yarn test
      - run: yarn ts
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
      - run: yarn serve &
        working-directory: web
      - run: yarn test
        working-directory: e2e
      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: e2e/test-results/*
